name: Shellcheck

on:
  push:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        uses: koalaman/shellcheck-action@v0.7.1
        with:
          shell: sh
        id: shellcheck
      - name: Print shellcheck errors
        run: echo "${{ steps.shellcheck.outputs.errors }}"
