name: MD CHeck
on: push
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run proselint on markdown files
        run: proselint *.md

# q: Its the above code correct? In case it's not, lets write the correct code
# a: The above code is correct. It will run proselint on all markdown files in the repository.
  