# q: How do I run proselint on all markdown files in a repository?
# Path: .github/workflows/simple.yaml
name: MD CHeck
on: push
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install proselint
        run: pip install proselint
      - name: Run proselint on markdown files
        run: proselint *.md

